services:
  grafana:
    user: root
    container_name: 'wazuh-datasource'

    ports:
      - 3000:3000/tcp
      - 2345:2345/tcp # delve
    security_opt:
      - 'apparmor:unconfined'
      - 'seccomp:unconfined'
    cap_add:
      - SYS_PTRACE
    volumes:
      - ../dist:/var/lib/grafana/plugins/wazuh-datasource
      - ../provisioning:/etc/grafana/provisioning
      - ..:/root/wazuh-datasource

    environment:
      NODE_ENV: development
      GF_LOG_FILTERS: plugin.wazuh-datasource:debug
      GF_LOG_LEVEL: debug
      GF_DATAPROXY_LOGGING: 1
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: wazuh-datasource
